<header id="header" class="header">
  <div class="img-decor"><img src="theme/images/bg/img-decor.jpg" alt=""/></div>
  <div class="logo"><img src="theme/images/logo.png" alt=""/></div>
  <div class="header-inner">
    <a class="nav-btn" href="#"></a>
    <nav class="nav">
      <ul>
        <li><a href="#">Home</a></li>
        <li><a href="#">Resources</a></li>
        <li><a href="#">About Us</a></li>
        <li><a href="#">Activities</a></li>
        <li><a href="#">Find Services</a></li>
        <li><a href="#">Calendar</a></li>
        <li><a href="#">Contact Us</a></li>
      </ul>
    </nav>
  </div>
</header>